version: "3.9"

services:
  mariadb:
    image: mariadb:latest
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - ${DB_PORT}:3306
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb-vl:/var/lib/mysql

volumes:
  mariadb-vl:
    driver: local
